[target.aarch64-unknown-linux-gnu]
pre-build = [
  "sudo dpkg --add-architecture arm64 && sudo apt-get update && sudo apt-get install --assume-yes g++ pkg-config libx11-dev libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev",
]
