name: Deploy

on: push
jobs:
  deploy:
    name: upload linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: sudo apt install g++ pkg-config libx11-dev libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
      - uses: Swatinem/rust-cache@v2
      - name: build binary
        run: cargo build --release --target x86_64-unknown-linux-gnu
