name: CI

on: 
  push:
    branches:
      - main
jobs:
  build-linux:
    name: upload linux to itch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

        # cache
      - uses: Swatinem/rust-cache@v2

      - name: install bevy dependencies
        run: sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev

      - name: build x86 release
        run: cargo build --release

      - name: rename file
        run: mv target/release/experiment ./linux_x86

      - name: upload to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux_x86
          ITCH_GAME: ${{ vars.GAME_ID }}
          ITCH_USER: ${{ vars.ITCH_USERNAME }}
          PACKAGE: linux_x86

  build-windows:
    name: build release binary for windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: build binary
        run: cargo build --release
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows_x86
          path: target\release\experiment.exe

  upload-windows:
    name: upload windows binary to itch
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: download release file
        uses: actions/download-artifact@v3
        with:
          name: windows_x86

      - name: rename file
        run: mv experiment.exe windows_x86.exe

      - name: upload to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows_x86
          ITCH_GAME: ${{ vars.GAME_ID }}
          ITCH_USER: ${{ vars.ITCH_USERNAME }}
          PACKAGE: windows_x86.exe
      - name: delete binary after upload
        uses: geekyeggo/delete-artifact@v1
        with:
          name: windows_x86

  build-mac-x86:
    name: build binary for macos
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: build x86 binary
        run: cargo build --release
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac_x86
          path: target/release/experiment

  build-mac-arm:
    name: build binary for macos on arm
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: add arm target
        run: rustup target add aarch64-apple-darwin
      - name: build arm binary
        run: SDKROOT=$(xcrun -sdk macosx --show-sdk-path) MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx --show-sdk-platform-version) cargo build --target=aarch64-apple-darwin --release
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac_arm
          path: target/aarch64-apple-darwin/release/experiment

  merge-mac:
    name: merge mac binaries
    needs: [build-mac-arm, build-mac-x86]
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: download x86 release file
        uses: actions/download-artifact@v3
        with:
          name: mac_x86
          path: ~/x86
      - name: download arm release file
        uses: actions/download-artifact@v3
        with:
          name: mac_arm
          path: ~/arm
      - name: run lipo to create universal binary
        run: lipo -create -output ~/mac_universal ~/arm/experiment ~/x86/experiment
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac_universal
          path: ~/mac_universal

      # cleanup
      - name: delete binary after upload
        uses: geekyeggo/delete-artifact@v1
        with:
          name: mac_arm
      - name: delete binary after upload
        uses: geekyeggo/delete-artifact@v1
        with:
          name: mac_x86
    
  
  upload-mac:
    name: upload macos binary to itch
    needs: merge-mac
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: download release file
        uses: actions/download-artifact@v3
        with:
          name: mac_universal

      - name: upload to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: mac_universal
          ITCH_GAME: ${{ vars.GAME_ID }}
          ITCH_USER: ${{ vars.ITCH_USERNAME }}
          PACKAGE: mac_universal
      - name: delete binary after upload
        uses: geekyeggo/delete-artifact@v1
        with:
          name: mac_universal

  build-linux-aarch64:
    name: build for linux on aarch64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: run commands
        id: runcmd
        with:
          arch: aarch64
          distro: bullseye
          run: |
            echo "installing dependencies"
            apt update
            apt install -y g++ pkg-config libx11-dev libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
            echo "installing rust"
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            cargo build --release
