name: CI

on: push
jobs:
  build-linux:
    name: upload linux to itch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

        # cache
      - uses: Swatinem/rust-cache@v2

      - name: install bevy dependencies
        run: sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev

      - name: build x86 release
        run: cargo build --release

      - name: upload to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux_x86
          ITCH_GAME: ${{ vars.GAME_ID }}
          ITCH_USER: ${{ vars.ITCH_USERNAME }}
          PACKAGE: target/release/experiment_1
  build-windows:
    name: build release binary for windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: build binary
        run: cargo build --release
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows_x86
          path: target/release/experiment_1

  upload-windows:
    name: upload windows binary to itch
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: download release file
        uses: actions/download-artifact@v3
        with:
          name: windows_x86

      - name: upload to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows_x86
          ITCH_GAME: ${{ vars.GAME_ID }}
          ITCH_USER: ${{ vars.ITCH_USERNAME }}
          PACKAGE: windows_x86
